### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GracjanFerenc** [PacktPublishing/Learn-Android-Programming-with-Kotlin#2]
I've got an error on this code
import kotlinx.android.synthetic.main.activity_main.*

"kotlinx" is highlighted red.

All "btnAdd" etc are red.

txtValue are all also red. 

please advise as app will not run and I'd like to test :)

**Comment by GracjanFerenc** [comment]
Fixed.

Added "id 'kotlin-android-extensions'" to build.gradle (:app)

**Comment by sarvesh-packt** [comment]
Hi @Speedabob 

Please Reopen if the issue still persist. 

Regards,
